# Generated by Django 4.1.5 on 2023-02-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("code_finder_api", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLoginTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(max_length=400, verbose_name="Access Token"),
                ),
                (
                    "refresh_token",
                    models.CharField(max_length=400, verbose_name="Refresh Token"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="code_finder_api.user",
                    ),
                ),
            ],
        ),
    ]
