# Generated by Django 4.1.5 on 2023-02-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_finder_api", "0005_codesnippet_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesnippet",
            name="language",
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name="codesnippet",
            name="public",
            field=models.BooleanField(default=None),
        ),
    ]
